### ISSUE TITLE
Feature limitation for different versions of type scripts

### ISSUE THREAD

**Issue by ShookLyngs** [sporeprotocol/spore-sdk#39]
In #31, a new version of SporeType is added to the testnet config, the new contract supports a lot of new features:
- Lock Proxy in Spore creation
- Cluster Proxy/Agent
- Spore Mutant
- ...

The mentioned new features are not supported in the previous version of SporeType. However, structurally, all versions of SporeType scripts share the same logic/codec in the spore-sdk. This could potentially lead to an issue where old versions of scripts may attempt to use new/unsupported features.

Therefore, we may need a design to separate different versions of scripts and limit their capabilities. For example, we can define a new prop `features` (map/object type) and define what feature can a specific version of script use:
```yaml
- SporeType
  tags: [v1]
  features:
    mutant: false
    clusterLockProxy: false
    clusterProxyAgent: false
- SporeType
  tags: [v2, latest]
  features:
    mutant: true
    clusterLockProxy: true
    clusterProxyAgent: true
```
